### ISSUE TITLE
Visibility doesn't work

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Content#70]
Trying to look at a page where visibility is set to "only logged in users" when not logged in works. That's obviously wrong:

![wrongvisibility](https://user-images.githubusercontent.com/19392292/27824505-0487729c-60ad-11e7-9a9b-291a6d7bf6e5.gif)

**Comment by Mihaiii** [comment]
Thanks for bringing this up!
This is actually related to the fact that the app checks the cookie and when SignIn app is stopped the cookie isn't deleted. You can see this [line](https://github.com/StarcounterApps/Content/blob/develop/src/Content/Api/ContentHandlers.cs#L96) .
If you log out and check a page that is protected, it would work as expected.

Since this is a portion of the code that I haven't touch, I would like a confirmation that the app shouldn't check for the cookie. :)

**Comment by Mihaiii** [comment]
I explained what happens in the previous message.
Closing.
